first_user = User.objects.create_user(username = "Ivanov Ivan")
second_user = User.objects.create_user(username = "Petrova Olga")
first_author = Author.objects.create(user=first_user)
second_author = Author.objects.create(user=second_user)
sp_category = Category.objects.create(category_name = "Sport")
he_category = Category.objects.create(category_name = 'Health')
po_category = Category.objects.create(category_name = 'Polity')
be_category = Category.objects.create(category_name = 'Beauty')
first_article = Post.objects.create(post_name = 'Life', post_text = 'text', post_author = first_author)
first_article.post_category.add(sp_category, he_category)
second_article = Post.objects.create(post_name = 'Children', post_text = 'text', post_author = first_author)
second_article.post_category.add(be_category, he_category)
first_news = Post.objects.create(post_name = 'Dabgerous', post_text = 'text',
                                    post_author = second_author, post_content = 'NE')
first_news.post_category.add(po_category, sp_category)
c1_comment = Comment.objects.create(comment_text = 'Excellent', post = first_article, user = second_user.user)
c2_comment = Comment.objects.create(comment_text = 'Bad', post = second_article, user = second_user.user)
c3_comment = Comment.objects.create(comment_text = 'Not bad', post = first_news, user = first_user.user)
c4_comment = Comment.objects.create(comment_text = 'Thanks', post = c1_comment, user = first_user.user)
first_article.like()
first_article.like()
second_article.dislike()
first_news.like()
c1_comment.like()
first_user.update_rating()
second_user.update_rating()
best_user= Author.objects.order_by('-rating').values('user__username', 'author__rating').first()
best_post = Post.objects.order_by('-post_rating').values('author__user__username', 'post_rating',
                                                         'post_time_in', 'post_name').first()
best_post
best_post.preview()
Comment.objects.filter(post=best_post).values('username', 'comment_time_in', 'comment_text', 'comment_rating')
